macro( ElastixComponent COMPONENT )
  ElastixModuleCheckName( ${COMPONENT} )
  set( ELASTIX_COMPONENT_{$COMPONENT}_DEFINED TRUE )
endmacro()

macro( ElastixComponentCheckName COMPONENT )
  if( NOT "${_name}" MATCHES "^[a-zA-Z][a-zA-Z0-9]*$" )
    message( FATAL_ERROR "Invalid component name: ${COMPONENT}" )
  endif()
endmacro()